export declare function styledConsoleLog(..._args: any[]): void;
export declare function getRedString(s: string): string;
export declare function getOrangeString(s: string): string;
export declare function getYellowString(s: string): string;
export declare function getGreenString(s: string): string;
export declare function getBlueString(s: string): string;
export declare function getPurpleString(s: string): string;
export declare function getBlackString(s: string): string;
export declare function getGrayString(s: string): string;
